package exception.trycatch;

public class ExceptionEx10 {

    public static void main(String[] args) throws Exception {

        throw new RuntimeException(); // Exception고의 발생
    }
}
